### ISSUE TITLE
Update Static Info on 'Refer a friend 'page

### ISSUE THREAD

**Issue by mathusham** [CS-GCC/codingchallengefrontend#114]
Currently the pages states there is a referral leaderboard and global referral winner.

Can this be changed to say there is an engagement leaderboard - with the referral badge (Social Butterfly) available for the contestant with the highest number of referrals.

**Comment by angeline-tech** [comment]
I haven't actually implemented the frontend stuff for the referral badge, i should be able to get it done over the weekend
