### ISSUE TITLE
Registered User asked to Fill out Sign Up Form Again.

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#116]
This is when you have signed up successfully. Filled out the form, got the success message etc. 
Sometimes the hasUserSignedUp doesn't get set properly. Going to make the change that Florian suggested and also make the question page call it before it redirects.

**Comment by tgjosephson** [comment]
I already signed up but when I tried to log in again, it prompted me to sign up again and I can't type in my university, and therefore can't get past the sign up screen to be able to answer any questions. Browser console shows the following error: 

Uncaught TypeError: e.toLowerCase is not a function
    i operations.ts:121
    Lodash 6
    search operations.ts:120
    r Redux
    handleSearchChange signUpModal.tsx:232
    onSearchChange signUpModal.tsx:138
    Lodash 4
    t Search.js:179
    Lodash 4
    t Input.js:78
    React 12
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
operations.ts:121:23
