### ISSUE TITLE
Sign Up: 'Course Title' Rewording

### ISSUE THREAD

**Issue by tgjosephson** [CS-GCC/codingchallengefrontend#133]
**Is your feature request related to a problem? Please describe.**
In the registration process, the form has a box for 'Course Title', this is not the most understandable term for those of us in the US. Adding 'Major' would make this more clear.

**Describe the solution you'd like**
Instead of 'Course Title', put 'Course Title/Major'.

**Comment by mathusham** [comment]
Also, 

On the sign-up form, when selecting region - **rename** 'Europe' to 'Europe (excluding UK and Switzerland)
