### ISSUE TITLE
Engagement leaderboard Fixes

### ISSUE THREAD

**Issue by FlorianLehmann** [CS-GCC/codingchallengefrontend#135]
Issue when calling the backend API.

{"timestamp":"2020-09-04T16:39:50.282+0000","status":500,"error":"Internal Server Error","message":"No value present","path":"/engagementLeaderboard/GLOBAL/"}

**Comment by angeline-tech** [comment]
Further error handling required. When an empty is returned it gets stuck on loading. Dev is fine. Do the same thing that happens on the individual leaderboard

**Comment by angeline-tech** [comment]
- [ ] Duplicates appearing in the engagement leaderboard. Happens at 20+. Think its to do with the load next? If it's a backend issue can you figure it out with them. 
- [ ] Handle the No Contestant thing
