### ISSUE TITLE
In-Browser Editor: Wrong skeleton appearing

### ISSUE THREAD

**Issue by tgjosephson** [CS-GCC/codingchallengefrontend#138]
When I go to Q1 and select 'Python' as the language for the in-browser editor, the editor comes up with the following message:
"this should be the code for question 1 in python".

This also happens for every language when I click on the drop down to change languages.

I have to click 'Reset' to get the correct skeleton to show.

Thanks.

**Comment by dragospopa** [comment]
#85

**Comment by angeline-tech** [comment]
Should be fixed by #85
