### ISSUE TITLE
Github submission information needed

### ISSUE THREAD

**Issue by tgjosephson** [CS-GCC/codingchallengefrontend#148]
For the users that are submitting their code through github instead of the in-browser editor, there should probably be detailed instructions on how to clone their personal repo and on how to commit their solutions. Kunal had quite detailed instructions in each language's README that made it really easy to get started. If we can find those instructions from past years, we could probably just copy what he had.

**Comment by angeline-tech** [comment]
@shreyanshrs44 is working on it
