### ISSUE TITLE
Improvement - More options in Region/University dropdown

### ISSUE THREAD

**Issue by FlorianLehmann** [CS-GCC/codingchallengefrontend#15]
**Is your feature request related to a problem? Please describe.**
During the previous coding challenge, a few persons were not able to select their universties on the Sign Up page.

**Describe the solution you'd like**
We could either try to extend the list of uni/regions or allow the user to add a new one.

**Additional context**

**Comment by jredpath6** [comment]
Options to be added:
- Currently, only a few universities/countries are listed
- If a student's region isn't listed they cannot be mapped to a region on the leaderboard
- Idea -- include a (other) : text box ? It would be a process of reviewing these additions and adding them to the list.

**Comment by jredpath6** [comment]
A possible use for Google Maps API:
https://developers.google.com/maps/documentation/javascript/examples/places-placeid-finder
