### ISSUE TITLE
Logging in when already signed up: Brought to registration form and then after a second successfullly registered.

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#150]
When logging into the server for the first time (after it being down). I was brought to the registration page, and then after a second, the "you have successfully registered" popup appeared. I have already signed up so should have gone straight to questions. 

For me it was only an issue the first time. Now when I log in and out it works as expected. Feels like an async issue? Maybe when you log in and out after doing it the first time, it just uses your cookies so the response is a lot quicker. On the first time it takes a while for you to get a response so you see the registration page. (redirected from questions). Once the call completes, the completed registration appears. 

Did anyone else find have this issue too?

**Comment by dragospopa** [comment]
Only happens when logging in through the green login button in Questions
