### ISSUE TITLE
Q3 Submission: Stuck 'In the Queue'

### ISSUE THREAD

**Issue by tgjosephson** [CS-GCC/codingchallengefrontend#151]
I submitted a basic 'return 1, 3' for python Q3 and clicked 'Run'. The 'In the Queue' pop up showed but it seems to be stuck in some infinite loop and won't stop. Browser console shows 'updating run status' an infinite number of times. Refreshing the page and/or clicking reset does not get me out of the loop. So I am not able to submit anything different.

**Comment by angeline-tech** [comment]
#85 This is being worked on. The backend request has failed for some reason. We are going to show a message explaining why. Will be done tomorrow most likely
