### ISSUE TITLE
Q3 skeleton input may not be right

### ISSUE THREAD

**Issue by tgjosephson** [CS-GCC/codingchallengefrontend#154]
I submitted a solution to Q3 in python and I am _fairly_ confident that it should be the correct solution. I have tested personally and it is correct. I think this is an issue with how the input is handled in the skeleton so that the wrong 'profit' parameter is getting sent to the user in the find_min_days function.

Can someone please take a look and see if there is an issue with the skeleton? Or maybe I just have a wrong solution submitted? Thanks

**Comment by angeline-tech** [comment]
@dragospopa have let backend team know.
