### ISSUE TITLE
Missing Badges

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#160]
isFewestAttempts - 
Neha http://gcc-global-dev.herokuapp.com/badge/5f468b0f6a0e1d000472ad27
Shweta 5f468003b79d43000475b7c8
Could be an issue with the **count function**. Displaying only 1. 

Social Butterfly Badge Rendering.

**Comment by angeline-tech** [comment]
Fastest Completion Uni is  missing for Neha
![image](https://user-images.githubusercontent.com/58768992/92328480-04b5cb80-f059-11ea-8690-95b32cab4b0d.png)

So is 1 Fewest Attempt Uni

**Comment by tgjosephson** [comment]
I am also missing the 'Completed all easy' badges even though the medium questions have been unlocked for me.

**Comment by angeline-tech** [comment]
This fix was merged yesterday
