### ISSUE TITLE
Show the question number for each badge

### ISSUE THREAD

**Issue by tgjosephson** [CS-GCC/codingchallengefrontend#165]
I have a good amount of badges but it would be nice if the description of the badge (which shows up when you hover over it) would say the question number that I received the badge for.

For example, I have the 'fewest lines of code in python' badge but I have no idea what question this badge was earned for. It would be nice to see that information included in the description when I hover over the badge.

**Comment by angeline-tech** [comment]
Also need to fix the living legend badge
