### ISSUE TITLE
Score Differences on leaderboards

### ISSUE THREAD

**Issue by tgjosephson** [CS-GCC/codingchallengefrontend#167]
My scores are different on the main leaderboard and the 'Question Results' tab when I click on my name.

**Main leaderboard**
Q1: 713
Q2: 681
Q3: 586

**Question Results**
Q1: 623
Q2: 645
Q3: 586

**Comment by angeline-tech** [comment]
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/58768992/92392828-d0a0e000-f116-11ea-8adb-0c4d5e25eec8.png">
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/58768992/92392860-d8f91b00-f116-11ea-9113-a00e4c498287.png">

@regalrr0 can you look into this please. Feel like it could be to do with the bonus points or something?

**Comment by regalrr0** [comment]
Raised issue to backend team as the response data we get for both the 'leaderboard/{region}' and 'contestant/stats/{id}' endpoints are different for a user.

[Check issue 103 for more details](https://github.com/CS-GCC/codingchallenge-global/issues/103)
