### ISSUE TITLE
Medium Questions Aren't Unlocking

### ISSUE THREAD

**Issue by tgjosephson** [CS-GCC/codingchallengefrontend#168]
I have completed all easy questions but the medium questions haven't been unlocked yet. I have 90/90 test cases correct for Q1 and Q2 and 88/90 test cases correct for Q3 but the medium questions are still locked for me.

I also don't have the 'completed all easy questions' engagement badge but that is less of a priority.

**Comment by angeline-tech** [comment]
Fixed by Backend Fix
