### ISSUE TITLE
Language field is null in request body of commitAnswer endpoint. (Major Bug) (High Importance)

### ISSUE THREAD

**Issue by shreyanshrs44** [CS-GCC/codingchallengefrontend#172]
For endpoint commitAnswer, language field is necessary as part of Request Body.
But I see for Question 1 and language :- cplusplus this field is null. Hence error is being thrown,
This need to be fixed asap.
@dragospopa @angeline-tech  Have a look at this , Is this same for any other question and language ? oh no
![image](https://user-images.githubusercontent.com/29723970/92410534-07e8ae80-f162-11ea-81d3-6c2d5d0ea20a.png)

For your ref:
keep language  names as (lower/uppercase doesnt matter)
    JAVA,
    PYTHON,
    CSHARP,
    JAVASCRIPT,
    CPLUSPLUS

**Comment by CS-CodingChallenge** [comment]
@FlorianLehmann is investigating the issue. So far it seems like its just C++ Submit.
We will check all combinations. Run/Submit in each language
