### ISSUE TITLE
Mobile View for Engagement and Individual Leaderboards

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#177]
### Engagement and Individual Leaderboards

Region and University are the only visible fields in mobile view, these should be switched to Bonus Points and Total Score if we can only have two columns.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/58768992/92418330-e4703480-f15e-11ea-93a4-421367684fd3.png">

**Comment by angeline-tech** [comment]
Looks like the full screen view has been affected. Can you take a look at this tomorrow @FlorianLehmann 
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/58768992/92533034-878d8080-f229-11ea-9a20-c9a66a77a4db.png">

**Comment by Deepthi-Rao** [comment]
^this has been fixed, centering the leaderboard

**Comment by angeline-tech** [comment]
Looks like this was actually done
<img width="350" alt="image" src="https://user-images.githubusercontent.com/58768992/96503855-c4e32600-124b-11eb-870d-08bbc0fe1a2c.png">
