### ISSUE TITLE
Make Support Email Address More Noticeable

### ISSUE THREAD

**Issue by tgjosephson** [CS-GCC/codingchallengefrontend#187]
This is a **very minor request** but can we make the support email address on the help page much more noticeable? I know of a few people who have had issues but have not sent an email to the support email address (that account has gotten 0 emails so far). I think it is because people don't notice the email address when they go to the help page.

Can we make another header above FAQs with the support email address or can we bold/red the address in the current light blue box?

Open to ideas on how to accomplish this.

**Comment by angeline-tech** [comment]
@tgjosephson we are adding back the submit query form as we have checked and its working.
@regalrr0 On the failure of that response, we still need to display a message giving the e-mail so could you make sure that on the failure message the e-mail is bold. Could you also make it a **mailto: link**
