### ISSUE TITLE
More Badge Fixes

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#192]
- [x] Show Score on the Badges
- [x] Fix the method that turns [1,2,3] into "Questions 1,2 and 3" Pop doesn't seem to work when deployed on the server
- [x] Social Butterfly only show the best badge

**Comment by mathusham** [comment]
-only show best badge (eg show global not regional and uni)
-show question each badge is associate to
-show points each badge is worth

**Comment by tgjosephson** [comment]
It also looks like the 'Early Bird' badge is only being given for question 1.  I can't find anyone who has gotten this badge for any of the other questions. Is this a frontend or backend issue?

Can someone look into this?

**Comment by angeline-tech** [comment]
![image](https://user-images.githubusercontent.com/58768992/92727509-24096d00-f367-11ea-96ba-96e94c7eff60.png)
Updated Bonus Point Badge Values
