### ISSUE TITLE
Fix Branding Issues

### ISSUE THREAD

**Issue by tgjosephson** [CS-GCC/codingchallengefrontend#218]
Mark Hirst from Branding had a list of things that need to be fixed to be in compliance with CS branding standards. It looks like a lot of items but they all seem to be relatively minor changes.

The list of items was went to the webapp DL from Mathusha, subject 'FW: Global Coding Challenge'.

**Comment by angeline-tech** [comment]
- [ ] Change All Messages to Have (Icon, Heading, Text, Link) - #f1f2f2 
- [ ] Change All Fluid Buttons to be CS Approved Square Black Buttons
- [ ] Verify that All Black Buttons are CS Approved Square Black Buttons
- [ ] Leaderboard Tabs - Use CS Defined UI Components (?)
- [ ] Set font to CS Type ET for all Grids (Leaderboard, Submission History, Profile Page)
- [ ] Casing on Refer A Friend page should be "Refer a friend"
- [ ] Remove Bolded CSS Fonts by adding to global CSS
- [ ] Make Question Cards have straight edges
- [ ] How To Play Page Accordions (Buttons & Text Alignment)
