### ISSUE TITLE
Change colour of 'Time is Money' badge to white

### ISSUE THREAD

**Issue by mathusham** [CS-GCC/codingchallengefrontend#226]
The 'time is money' badge is the only badge which shows up in black, changing this to white would match up with the rest of the badges.

**Comment by mathusham** [comment]
![Screenshot 2020-09-24 at 11 13 16 pm](https://user-images.githubusercontent.com/36700905/94205604-890ea800-febb-11ea-879c-7d2782670d39.png)

**Comment by angeline-tech** [comment]
Corrected typo in import statement
![Uploading image.png…]()
