### ISSUE TITLE
Questions not unlocking

### ISSUE THREAD

**Issue by mathusham** [CS-GCC/codingchallengefrontend#231]
I have completed all easy questions (ID is 5f6e09c3107226000487d9ab):

![Screenshot 2020-09-25 at 5 03 28 pm](https://user-images.githubusercontent.com/36700905/94289717-09cbb380-ff51-11ea-8eff-992e5a124ce5.png)

but the medium questions are not unlocking for me:

![Screenshot 2020-09-25 at 5 04 21 pm](https://user-images.githubusercontent.com/36700905/94289793-29fb7280-ff51-11ea-9cc2-571bf8819b39.png)

**Comment by angeline-tech** [comment]
Closing this as it's a [backend issue](https://github.com/CS-GCC/codingchallenge-global/issues/153). The endpoint we use for the unlocking is 
[contestant/git](https://gcc-global-dev.herokuapp.com/contestant/git/mathusham)
