### ISSUE TITLE
Misc Branding Qualms

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#247]
**Help Page** 
- [x] Align the Button
- [x] Make FAQs smaller but in bold
**HomePage**
- [x] Space between Elements
- [x] Squaring the "Tab" at the bottom of the map
Leaderboard
- [x] Add breakpoints to move the elements down
Refer A Friend
- [x] Add breakpoints to move the elements down
News Page 
- [x] Button Slightly to the left inline with Text
Howto Play Page 
- [x] Update Globe to be larger image

**Comment by regalrr0** [comment]
Committed help page fixes to bug/brandingHelp
