### ISSUE TITLE
Article Formatting

### ISSUE THREAD

**Issue by mathusham** [CS-GCC/codingchallengefrontend#273]
Badge names are in the incorrect bold

https://files.slack.com/files-pri/T0182MGS7TM-F01BV7EELLF/image.png

**Comment by angeline-tech** [comment]
Need to do some CSS overrides on the article page.
Bolds <b> need to render in CS TYPE BOLD
The alignment of the paragraphs is a bit off. Should all be straight - Probable need a 0 margin
Bullet Points aren't rendering properly.
Work with @YashashreeKolhe on the details
