### ISSUE TITLE
PDFs not loading properly - Caching Issue

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#283]
Can't test it on local.
We want to use the PDFs from the Public folder so that the url hasn't changed.
Some Node BS.
[Using the Public Folder](https://create-react-app.dev/docs/using-the-public-folder/)

Something to do with the starter.js file I think

**Comment by CS-CodingChallenge** [comment]
Reverted back to using the imported javascript method. Left the ones in the public folder but all links use the javascript ones
