### ISSUE TITLE
Signup completion display 

### ISSUE THREAD

**Issue by shreyanshrs44** [CS-GCC/codingchallengefrontend#286]
![image](https://user-images.githubusercontent.com/29723970/96210576-d698a500-0f8f-11eb-91d9-e528443cb04c.png)
After signup I cannot goto any page from here until unless I click refer friend or hit refresh. I see this as a bad ui experience. 
Thanks !

**Comment by angeline-tech** [comment]
We did it this way on purpose to kind of force people to go to refer a friend. 
If people sign up after the challenge has started it should say "start answering questions now" and take them directly to questions. 
I'll leave the issue open just in case we get any support queries about this but so far no one has complained about it.
