### ISSUE TITLE
Leaderboard Fixes

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#34]
**Individual - Global **
Change Country to Region
Add Column for Badges (Score only)
Dropdown to select region
Dropdown to select University
-- Rankings to adjust accordingly
Speak to Backend to keep track of region/university ranking

**University Leaderboard**
Dropdown to Select Region
Add extra columns for questions

**Engagement**
Columns
-- Ranking
Name
Uni
Region
Number of Badges (Engagement only)
Total Score (From Engagement Badges only)

Dropdown for region and universities

**Comment by FlorianLehmann** [comment]
Update API

**Comment by angeline-tech** [comment]
Add Region to Region Column using the new endpoint
We aren't doing badge count any more as the object is too confusing. 
We are going to change it to : "Bonus Points"
This filled using the "total" field in the question number "0" object. 

Let us know if you have any issues
