### ISSUE TITLE
Leaderboard Bugs

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#63]
- [x] Infinite Scroll on Individual Leaderboard doesn't work
- [x] Search on Leaderboard doesn't work
- [x] Search on University Leaderboard doesn't work
- [x] University Leaderboard Reset doesn't work
- [x] Region should be before University
- [x] Only select one Region
- [x] University dropdown should populate based off region

 Branch -> fix/Leaderboard-Bugs

**Comment by FlorianLehmann** [comment]
Region dropdown is only working for India and the UK. The API for the new regions doesn't exist yet.
