### ISSUE TITLE
Add "Other University" option to the Sign Up Page

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#86]
If a user can't find their University in the dropdown list for their Region, they need a way of getting their uni added to the DB.

### Basic Idea
Add a "can't see your uni" button to the sign up page.
Opens a Modal or something with a form. 
Auto-fill Github Username
Region Drop down
University Name
"Request"
This goes to the backend...

### Question
Do we want the University to be instantly added to the DB? Or do we want some review process.
If we have a review process, how long is it going to take. 
What do we say to the user?
`thanks, come back tomorrow`
They should still be able to sign up. Maybe we set it temporarily as other and we'll correct it later once its been reviewed?
Do we send them an e-mail to let them know its been added/changed?

**Comment by tgjosephson** [comment]
After our call discussing this:
- There will be an 'Other' option listed for each region
- The signup form should have a note saying 'If you don't see your university listed, please choose the 'Other' option and send us a support ticket with your name and university'
- If the user selects 'Other' then maybe a button appears to submit a support query
- The user will be able to participate in the challenge while they are listed under 'Other' university and then when the uni gets approved and changed by the support team, all of their points will transfer

**Comment by angeline-tech** [comment]
Need backend to add Other to each region of the DB so that the post request for submitting actually goes through. Atm it returns a 404 error. 
@mathusham @RalucaLusca @tgjosephson Can you confirm the e-mail that gets sent is ok.

**Comment by RalucaLusca** [comment]
I think it looks fine. We shouldn't need any more info that that. No? @mathusham @tgjosephson 
Thanks for making the changes!
