### ISSUE TITLE
Markdown for Questions

### ISSUE THREAD

**Issue by angeline-tech** [CS-GCC/codingchallengefrontend#91]
The automatic styling of the markdown isn't too great. 
May have to do some overrides. Code Blocks don't show up as separate blocks.
Quotes, Code Blocks, Headings etc.

**Comment by mathusham** [comment]
Q1: 
add **bullet points** for constraints
examples: Command line input and Number of predicted days and Sequence of predicted share prices **should be in code**

Q2:
add **bullet points** for constraints
examples: Command line input and Number of predicted days and A sequence of predicted share prices **should be in code**

Q3: 
add **bullet points** for constraints
Input Format and Constraints: add **subscript** properly for Ni and Di
Output Format: 'The buy and sell days for different profits should be separated by ,.' **comma should be in code**
examples: Command line input **should be in code**

Q4:
add **bullet points** for first paragraph
Input Format: add **subscript** properly for pi xi yi
add **bullet points** for constraints
examples: Command line input **should be in code**

Q5:
add bullet points for constraints
Input Format: ' the preference of each person is separated by  ,. ' **comma should be in code**
Input Format: example  **should be in code**
examples: Command line input **should be in code**

Q6:
add **bullet points** for constraints
floor(squareRoot(stringLength)) <= matrixRows <= matrixColumns <= ceil(squareRoot(stringLength)) and
matrixRows x matrixColumns >= stringLength   **should be in code**
examples: Command line input and matrix **should be in code**

Q7:
first paragraph User A answers User B's question and User B answers User A's question and
If two or more users, which are considered suspicious, answer user C's question then user C is also considered suspicious. should be **bullet points** 
add **bullet points** for constraints
Input Format: ' Each question detail is separated by ,. ' **comma should be in code**
Input Format: example  **should be in code**
Output Format: example  **should be in code**
Output Format: 'A string that contains all suspicious User ID(s), separated by ,.' **comma should be in code**
examples: Command line input **should be in code**

Q8:
add **bullet points** and **sub bullet points** for Input Format
Example 1 output: numbered points 1-11 should be a **numbered list**
examples: Command line input **should be in code**

Q9:
**space** out (txt)
more **space** between ALL tables and paragraphs
'every box has only transactions of the same type' should be **bullet pointed.**
input format: 'integer t represents the number of boxes...' and 'the next t lines contains integers...' should be **bullet pointed**
add **bullet points** for constraints
Output Format: 'These strings should be separated by , ' **comma should be in code**
examples: Command line input **should be in code**

**Comment by angeline-tech** [comment]
@rgardner6 @mathusham can you guys work together on this. We'd like to get this fixed in and released at some point this week. Ideally by Wednesday.

**Comment by rgardner6** [comment]
Fixed all the questions, other than possibly Q9 (tables might not get formatted properly with new markdown parser yet), and there was a bit of a confusing point on Q4. Q4 has the issue "Input should be 4 2" but it doesn't say whether thats an issue for example 1 or 2, so I left it unchanged. If that needs to be changed we can submit the question again no problem with the fix. Leaving this issue open until Q9 tables are fixed or we reach a compromise/change how the question is presented.

**Comment by mathusham** [comment]
@tgjosephson @RalucaLusca Pls check all markdown updates are here : )

**Comment by tgjosephson** [comment]
@rgardner6 'Input should be 4 2' is referencing the first line of input for example 1. The output of 1.5 is correct, but in the explanation, it should be 'm=2' **not** 'm=3'.

@mathusham The rest looks good:)
